name: Python Deployment

on:
  push:
    branches:
      - main  # Adjust this to your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Deploy app
      run: python app.py
